version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
    ignore:
      - dependency-name: "typescript"
        versions: [">=5.0.0"]
      - dependency-name: "chalk"
        versions: [">=5.0.0"]
      - dependency-name: "react-chartjs-2"
        versions: [">=5.0.0"]

  - package-ecosystem: "npm"
    directory: "/release/app"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
