name: CI

on:
  pull_request:
  push:
    branches: [main, master]

permissions: read-all

jobs:
  build:
    permissions:
      contents: read
    uses: ./.github/workflows/build.yml

  test:
    permissions:
      contents: read
    uses: ./.github/workflows/test.yml

  e2e:
    needs: build
    permissions:
      contents: read
    uses: ./.github/workflows/e2e.yml
